### ISSUE TITLE
[Indexer] Ethereum indexer fails when syncing

### ISSUE THREAD

**Issue by bridgedragon** [swapper-org/NodeChain#177]
- [x] I have read the [Contributing](https://github.com/swapper-org/NodeChain/blob/master/CONTRIBUTING.md) file of the documentation.
- [x] I have searched the [issues](https://github.com/swapper-org/NodeChain/issues) (including closed ones) and believe that this is not a duplicate.

## Issue
The following error is thrown when indexer is running in testnet.
```
2022-05-06 10:03:13,160 - INFO - Current block in index 3464364. Current block in ETH chain: 12242022
Traceback (most recent call last):
  File "./indexer.py", line 169, in <module>
    main()
  File "./indexer.py", line 123, in main
    insertBlockTransactions(web3=web3, blockNumber=blockNumber, numTxs=numTxs, cur=cur)
  File "./indexer.py", line 159, in insertBlockTransactions
    logger.info(f"Skipping {tx['txhash'].hex()} tx. Incorrect contract_to length: {len(contractTo)}")
  File "/usr/local/lib/python3.6/site-packages/web3/datastructures.py", line 51, in __getitem__
    return self.__dict__[key]  # type: ignore
KeyError: 'txhash'
```

**Comment by 0xp3gasus** [comment]
Bug fixed in https://github.com/swapper-org/eth-transactions-indexer/pull/2
